### ISSUE TITLE
Example Docker-Compose Network Routing With OTBR

### ISSUE THREAD

**Issue by melonchucker** [openthread/ot-br-posix#652]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is.
I had a difficult time getting a docker-compose network up and running without using `network_mode: host`.  I and many others use docker-compose as an easy way of sharing "portable" networks with others and for prototyping.  Having a section in the OTBR documentation showing how to set up a docker-compose network using the OTBR to route between a user container and an OT node would be very helpful.  Some of these difficulties are partially due to Docker being a little rough around the edges with IPV6 support, but a template would remove some friction in adopting/integrating OT.

**Describe the solution you'd like** A clear and concise description of what you want to happen.
A docker compose project with instructions providing a network configuration between a user docker container and a remote OT node.  The steps should show setting up a static ip for the OTBR in the docker-compose.yml and routing traffic from the user container to the OT nodes (e.g. `ip -6 route <on_mesh_prefix>/64 via <OTBR_ip>` on the user container).  It could be as simple as echoing CoAP messages but would be useful to see how to add containers to the mesh network.  This would fit nicely in the [Docker section](https://openthread.io/guides/border-router/docker/) of the OT guide.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
N/A

**Additional context** Add any other context or screenshots about the feature request here.

I haven't created a CoAP proxy but was able to get my container running with something similar to this.
Here's a partial docker-compose.yml
```
version: "2.1"

services:
   openthread_border_router:
     image: openthread/otbr
     volumes:
       - /dev/ttyACM0:/dev/ttyACM0
     sysctls:
       net.ipv6.conf.all.disable_ipv6: 0
       net.ipv4.conf.all.forwarding: 1
       net.ipv6.conf.all.forwarding: 1
     ports:
       - 8080:80
     dns:
       - 127.0.0.1
     privileged: true
     command: ["--radio-url", "spinel+hdlc+uart:///dev/ttyACM0"]
     # network_mode: host
     networks:
       ipv6net:
          ipv6_address: 2001:3984:3989::20

   coap_logger:
     build: ./coap_logger
     command: ["python", "coap_echo.py"]
     # network_mode: host
     networks:
      - ipv6net
     cap_add:
       - NET_ADMIN

 networks:
   ipv6net:
     driver: bridge
     enable_ipv6: true
     ipam:
       driver: default
       config:
       - subnet: 2001:3984:3989::/64
         gateway: 2001:3984:3989::1
```

Routing the traffic from user container to the OT node

Set On-Mesh prefix in OTBR web interface:
![image](https://user-images.githubusercontent.com/43282567/102269419-3654f300-3ee2-11eb-90e4-7c073cd85297.png)

Route traffic to OT nodes (Set on user container, could be added to user Dockerfile?):
`ip -6 route add <ot_mesh_prefix> via <otbr_static_ip>` => `ip -6 route add fd11:22::/64 via 2001:3984:3989::20`
